spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptopayments
    username: admin
    password: admin123
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          time_zone: UTC

    show-sql: true

base:
  rpc-url: ${BASE_RPC_URL:http://localhost:8545}

usdc:
  contract: ${USDC_CONTRACT:0x0000000000000000000000000000000000000000}

server:
  port: 8080